modLoader="javafml" #mandatory
loaderVersion="[37,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
issueTrackerURL="https://github.com/itayfeder/modjam/issues" #optional
[[mods]] #mandatory
modId="aritsu" #mandatory
version="${file.version}" #mandatory
displayName="Example Mod" #mandatory
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
logoFile="examplemod.png" #optional
credits="" #optional
authors="ItayFeder, Arinav, Subaraki" #optional
description='''
Mod Description
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.aritsu]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[37,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.aritsu]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,)"
    ordering="NONE"
    side="BOTH"
